# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'SwiftMVVMTemplate' do
  # Networking
  pod 'Moya/RxSwift'  # https://github.com/Moya/Moya
  pod 'Apollo', '0.33.0'  # https://github.com/apollographql/apollo-ios

  # Rx Extensions
  pod 'RxDataSources', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxDataSources
  pod 'RxSwiftExt', '~> 5.0'  # https://github.com/RxSwiftCommunity/RxSwiftExt
  pod 'NSObject+Rx', '~> 5.0'  # https://github.com/RxSwiftCommunity/NSObject-Rx
  pod 'RxViewController', '~> 1.0'  # https://github.com/devxoul/RxViewController
  pod 'RxGesture', '~> 3.0'  # https://github.com/RxSwiftCommunity/RxGesture
  pod 'RxOptional', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxOptional
  pod 'RxTheme', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxTheme

  # JSON Mapping
  pod 'Moya-ObjectMapper/RxSwift', '~> 2.0'  # https://github.com/ivanbruel/Moya-ObjectMapper

  # Image
  pod 'Kingfisher', '~> 6.0'  # https://github.com/onevcat/Kingfisher

  # Date
  pod 'DateToolsSwift', '~> 5.0'  # https://github.com/MatthewYork/DateTools
  pod 'SwiftDate', '~> 6.0'  # https://github.com/malcommac/SwiftDate

  # Tools
  pod 'R.swift', '~> 5.0'  # https://github.com/mac-cain13/R.swift
  pod 'SwiftLint', '0.42.0'  # https://github.com/realm/SwiftLint

  # Keychain
  pod 'KeychainAccess', '~> 4.0'  # https://github.com/kishikawakatsumi/KeychainAccess

  # UI
  pod 'NVActivityIndicatorView', '~> 4.0'  # https://github.com/ninjaprox/NVActivityIndicatorView
  pod 'ImageSlideshow/Kingfisher', '~> 1.8'  # https://github.com/zvonicek/ImageSlideshow
  pod 'DZNEmptyDataSet', '~> 1.0'  # https://github.com/dzenbot/DZNEmptyDataSet
  pod 'Hero', :git => 'https://github.com/HeroTransitions/Hero.git', :branch => 'develop'  # https://github.com/lkzhao/Hero
  pod 'Localize-Swift', '~> 3.0'  # https://github.com/marmelroy/Localize-Swift
  pod 'RAMAnimatedTabBarController', '~> 5.0'  # https://github.com/Ramotion/animated-tab-bar
  pod 'AcknowList', '~> 1.8'  # https://github.com/vtourraine/AcknowList
  pod 'KafkaRefresh', '~> 1.0'  # https://github.com/OpenFeyn/KafkaRefresh
  pod 'WhatsNewKit', '~> 1.0'  # https://github.com/SvenTiigi/WhatsNewKit
  pod 'Highlightr', '~> 2.0'  # https://github.com/raspu/Highlightr
  pod 'DropDown', '~> 2.0'  # https://github.com/AssistoLab/DropDown
  pod 'Toast-Swift', '~> 5.0'  # https://github.com/scalessec/Toast-Swift
  pod 'HMSegmentedControl', '~> 1.0'  # https://github.com/HeshamMegid/HMSegmentedControl
  pod 'FloatingPanel', '~> 1.0'  # https://github.com/SCENEE/FloatingPanel
  pod 'MessageKit', '~> 3.0'  # https://github.com/MessageKit/MessageKit
  pod 'MultiProgressView', '~> 1.0'  # https://github.com/mac-gallagher/MultiProgressView
  
  # Keyboard
  pod 'IQKeyboardManagerSwift', '~> 6.0'  # https://github.com/hackiftekhar/IQKeyboardManager

  # Logging
  pod 'CocoaLumberjack/Swift', '~> 3.0'  # https://github.com/CocoaLumberjack/CocoaLumberjack
  
end